output "name" {
  value = proxmox_virtual_environment_vm.this.name
}

output "vm_id" {
  value = proxmox_virtual_environment_vm.this.vm_id
}

output "ipv4_address" {
  description = "First non-loopback IPv4 reported by qemu-guest-agent (CNI/docker interfaces skipped)."
  value       = try(local.usable_ipv4[0], null)
}

output "mac_address" {
  description = "MAC of net0 (set from variable, or generated by Proxmox)."
  value       = try(proxmox_virtual_environment_vm.this.network_device[0].mac_address, null)
}
